# This is a basic workflow to help you get started with Actions
name: 02-1. Simple Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Run node.js version
        run: |
          node -v
  
  # Running jobs in a container - Use a container to run the steps in a job.
  container:
    name: Container
    runs-on: ubuntu-latest
    container:
      image: node:14.15.0-alpine3.12

    steps:
      - name: Run inside container
        run: |
          node -v
          cat /etc/os-release 
          echo Hello Node from Container
      
      - name: Use another container
        uses: docker://node:12.14.1
        with:
          entrypoint: /bin/cat
          args: /etc/os-release
